CREATE CACHED TABLE USER(
    "ID" INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    "ACCOUNT_KEY" VARCHAR(100),
    "NAME" VARCHAR(50),
    "TOKEN" CHAR(36),
    "GMT_CREATE" BIGINT,
    "GMT_MODIFIED" BIGINT
)




